### ISSUE TITLE
Error: Could not load service "@dashevo/dashd-rpc" as it does not support necessary methods and properties.

### ISSUE THREAD

**Issue by yourtechcare** [dashevo/dashd-rpc#25]
Error: Could not load service "@dashevo/dashd-rpc" as it does not support necessary methods and properties.

**Comment by yourtechcare** [comment]
Error: Could not load service "@dashevo/dashd-rpc" as it does not support necessary methods and properties.
    at checkService (/usr/local/lib/node_modules/@dashevo/dashcore-node/lib/scaffold/start.js:124:11)
    at Function.setupServices (/usr/local/lib/node_modules/@dashevo/dashcore-node/lib/scaffold/start.js:182:7)
    at start (/usr/local/lib/node_modules/@dashevo/dashcore-node/lib/scaffold/start.js:85:31)
    at Command.<anonymous> (/usr/local/lib/node_modules/@dashevo/dashcore-node/lib/cli/main.js:70:7)
    at Command.listener (/usr/local/lib/node_modules/@dashevo/dashcore-node/node_modules/commander/index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
    at Command.parseArgs (/usr/local/lib/node_modules/@dashevo/dashcore-node/node_modules/commander/index.js:651:12)
    at Command.parse (/usr/local/lib/node_modules/@dashevo/dashcore-node/node_modules/commander/index.js:474:21)
    at Object.main (/usr/local/lib/node_modules/@dashevo/dashcore-node/lib/cli/main.js:147:11)
/usr/local/lib/node_modules/@dashevo/dashcore-node/lib/scaffold/start.js:124

**Comment by antouhou** [comment]
@yourtechcare It looks like you're running an instance of https://github.com/dashevo/dashcore-node with an invalid config file that specifies "@dashevo/dashd-rpc" as a service. This library is not a service of dashcore-node. You can check https://github.com/dashevo/dashcore-node#configuration to see how to configure `dashcore-node`

**Comment by yourtechcare** [comment]
Possible for you to guide, how to enable RPC with dashcore-node without installing dashd-rpc?

**Comment by antouhou** [comment]
RPC server is a part of https://github.com/dashpay/dash, you don't need any additional software to make RPC work

**Comment by yourtechcare** [comment]
Fatal error:  Uncaught exception 'RuntimeException' with message 'Unable to connect to http://dash:local321@xx.xx.xx.xx:9998/ Error: Failed to connect to xx.xx.xx.xx port 9998: Connection refused' in C:\xampp\htdocs\dash\jsonRPCClient.php:231

**Comment by yourtechcare** [comment]
dash-cli command also giving error related RPC

**Comment by antouhou** [comment]
Please check your dash configuration file to see the RPC server configuration. The file is usually located under ~/.dashcore/dash.conf, but it is possible to specify another file. It should look like this:
```
server=1
daemon=1
rpcuser=USERNAME
rpcpassword=PASSWORD
```
It's also possible to specify a different port here. If all the configs are presented in the file, then it's most likely that you're trying to access RPC with a wrong address, port or user password

**Comment by yourtechcare** [comment]
Thank you very much !
